dataset: meta-dataset-select
train_set_args: 
  split: meta-train
  size: 224           
  transform: mocov3
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
  domains:
    - quickdraw
    - ilsvrc_2012
    - omniglot
    - fungi
    - vgg_flower
    - aircraft
    - cu_birds
val_dataset: meta-dataset
val_set_args:
  split: meta-val
  size: 224           # added for ViT
  transform: clip
  n_batch: 50
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
  domains:
    - mscoco



encoder: mocov3_vit
encoder_args: 
  # arch: vit_small
  # ckpt_path: ../pretrained_model/mocov3/vit-s-300ep.pth.tar
  arch: vit_base
  ckpt_path: /datadrive/pretrained_model/mocov3/vit-b-300ep.pth.tar


# path: /datadrive2/save/meta_dataset/mocov3/mscoco/qoi/meta-dataset_mocov3_vit_fs-centroid_15y2s18q_300m_100M
# ckpt: epoch-10.pth
# start_epoch_from: 10

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-5
  momentum: 0.9
  weight_decay: 0


########### M,m trend
save_path: ./save/mocov3/domain-net/Mm_trend


save_epoch: 10
V: 1
n_epochs: 10
