dataset: meta-dataset
train_set_args: 
  split: meta-train
  size: 224           # added for ViT
  transform: clip
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 9
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
  domains:
    - None
val_dataset: meta-dataset
val_set_args:
  split: meta-val
  size: 224           # added for ViT
  transform: clip
  n_batch: 50
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 10
  deterministic: True  # whether set images in dataset to be deterministic in each epoch
  domains:
    - mscoco


encoder: clip_ViT-B32

# path: /datadrive2/save/meta_dataset/clip/mscoco/qoi/meta-dataset_clip_ViT-B32_fs-centroid_15y2s18q_300m_100M
# ckpt: epoch-30.pth
# start_epoch_from: 30

classifier: fs-centroid
classifier_args:
  temp: 10.
  learn_temp: True

optimizer: sgd
optimizer_args:
  lr: 1.e-5 # 0.001
  momentum: 0.9
  weight_decay: 5.e-6


########### M,m trend
save_path: /mnt/disk/select_data/save/clip/domain-net/real_split


save_epoch: 5
V: 1
n_epochs: 10

