dataset: meta-dataset
test_set_args:
  split: meta-test
  size: 224                 
  transform: clip
  n_batch: 100
  n_episode: 2
  n_way: 15
  n_shot: 1
  n_query: 9
  domains:
    - quickdraw


encoder: clip_ViT-B32
ckpt: max-va.pth
# ckpt: epoch-5.pth

classifier: fs-centroid
classifier_args:
  temp: 10.

V: 1
n_epochs: 10
